Parameters:
  ClouSecMainAccountID:
    Type: String
    Description: Enter the ClouSec Main Account ID
  
  ClouSecMainAccountRoleName:
    Type: String
    Default: EC2ECRCrossAccessRole
    Description: Enter the ClouSec Main Role Name

  Rolename:
    Type: String
    Default: clousec-inspector-readonly-role-ec2
    Description: Enter the Inspector Role Name

Resources:
  InspectorReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: !Ref Rolename
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              AWS: 
                Fn::Sub: "arn:aws:iam::${ClouSecMainAccountID}:role/${ClouSecMainAccountRoleName}"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonInspector2ReadOnlyAccess" # Read-only access
      Policies:
        - PolicyName: InspectorCustomPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - inspector:UpdateFindings
                Resource: "*"

Outputs:
  InspectorRoleArn:
    Description: ARN of the InspectorReadOnlyRole
    Value: !GetAtt InspectorReadOnlyRole.Arn
